angle = 0;
depth = +10;
time = 0;
image_xscale = -1;
die_volting = false;
die = false;
can_jump_on_head = false;
hp = 3;
flat = false;
stomped_delay = 0;
flying_back= false;
takendamage = 0;
draw_xscale = 0;
draw_yscale = 0;
redblinktimer = 0;
has_seen_player = false; /*If boss hasn't seen player, then don't activate the fight yet.*/
arrow_xscale = 0;
stuck_in_wall_counter = 0;
sliding_along_ground = 0;