global.part_limit --;
global.part_limit_text_alpha = 1;
switch(object)
{
	case LEVEL_OBJECT_ID.ID_ENEMY_BOWLINGBALL:
	case LEVEL_OBJECT_ID.ID_ENEMY_BOWLINGBALL_BLIND:
	case LEVEL_OBJECT_ID.ID_ENEMY_BOWLINGBALL_BLIND_COIL_SPRING:
	case LEVEL_OBJECT_ID.ID_ENEMY_BOWLINGBALL_COIL_SPRING:
	case LEVEL_OBJECT_ID.ID_BASIC_ENEMY:
	case LEVEL_OBJECT_ID.ID_BASIC_ENEMY_BLIND:
	case LEVEL_OBJECT_ID.ID_BASIC_ENEMY_BLIND_COIL_SPRING:
	case LEVEL_OBJECT_ID.ID_BASIC_ENEMY_COIL_SPRING:
	case LEVEL_OBJECT_ID.ID_BIG_STATIONARY_ENEMY:
	case LEVEL_OBJECT_ID.ID_BIG_STATIONARY_ENEMY_COIL_SPRING:
	case LEVEL_OBJECT_ID.ID_BOSS:
	case LEVEL_OBJECT_ID.ID_WARP_BOX:
	case LEVEL_OBJECT_ID.ID_WARP_BOX_ONE_USE:
		global.part_limit_entity --;
		global.part_limit_entity_text_alpha = 1;
		break;
}