sprite_index = global.resource_pack_sprite_basic_enemy;
mask_index = spr_wall;
move_speed = 4; /* Slower than player, so that they're noticable when traveling */
delay = 1;
enter_level_delay = 0;
enter_level_y = 0;
come_from_level = -1;
xx = x;
yy = y;
gravity = 0;
alarm[0] = 1;
depth = -10;